### ISSUE TITLE
Drop requirement for sqlalchemy-migrate (deprecated, not supported with SQLAlchemy v2+)

### ISSUE THREAD

**Issue by patjoly** [pytrainer/pytrainer#240]
As you know, starting with version 2.0 sqlalchemy no longer supports sqlalchemy-migrate. As a work-around, pytrainer now requires a version of sqlalchemy <= 1.46 which is a work-around for the time being but not sustainable long-term.

I am no expert in database migration but would like to begin working on a conversion to alembic as a data migration tool.  I would suggest that a feature branch be created so that people could contribute to this effort, with all of the necessary unit tests to ensure that databases get migrated safely.

**Comment by viiru-** [comment]
Since the last time we added a migration was in version 1.12.0 (released in early 2018) when porting pytrainer to SQLAlchemy, we were actually planning to simply drop the existing migrations and support for databases generated before that instead of starting a complex project to re-create the existing migrations in alembic.

It wouldn't hurt to write code to detect a database schema that is so badly out of date and fail with a useful error message ("Please use version 2.1.0 to migrate this database", or something).
