### ISSUE TITLE
Tag a new official release (and release early, release often)

### ISSUE THREAD

**Issue by AMDmi3** [pytrainer/pytrainer#86]
As I can see latest official release is 1.10.0 from back 2013. Since the development goes on, distros begin to package snapshots and make unofficial releases, like 1.10.1 and 1.10.2 in Debian/Ubuntu:

https://repology.org/metapackage/pytrainer

which confuse users. Would be nice if newer official release was tagged.

**Comment by viiru-** [comment]
It has been a very long time since the last release, you are right. However the project has only been "under new management" for a couple of months, and in that time I haven't been able to solve any of the major issues (which are blockers for the distributions, pytrainer will not be shipped in them without removing the requirement for python-webkit).

I could of course create a release anyway, and perhaps I'll do that at some point. I haven't yet given up hope on being able to release a version that can go into the distributions, and be available for users to install. I would very much appreciate any help in this, see issue #40 for a list of what needs to be done (and pr #84 for a start toward the first step).
